project:
  type: website
  output-dir: _site

website:
  title: "Weldy Lab"
  site-url: "https://weldylab.org"

  google-analytics: "G-EVBRMBPE47"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: people.qmd
        text: People
      - href: medicine.qmd
        text: Medicine
      - href: publications.qmd
        text: Publications
      - href: news/
        text: News
      - href: join.qmd
        text: Join
      - href: contact.qmd
        text: Contact

  page-footer:
    left: "Â© Weldy Lab"
    right:
      - icon: github
        href: https://github.com/

format:
  html:
    theme: cosmo
    toc: true
    smooth-scroll: true
    css: styles.css
    favicon: images/WeldyLabLogo.jpg
